"""supervision

Revision ID: 1d606bec3a76
Revises: 299453df7836
Create Date: 2026-08-21 19:05:35.280971
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d606bec3a76'
down_revision: Union[str, None] = '299453df7836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor_relationship',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('supervisor_person_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('primary', 'co_supervisor', 'additional', name='supervisor_role'), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'accepted', 'active', 'changed', 'ended', name='supervision_status'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_supervisor_relationship_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_person_id'], ['person.id'], name=op.f('fk_supervisor_relationship_supervisor_person_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supervisor_relationship'))
    )
    op.create_index(op.f('ix_supervisor_relationship_student_id'), 'supervisor_relationship', ['student_id'], unique=False)
    op.create_index(op.f('ix_supervisor_relationship_supervisor_person_id'), 'supervisor_relationship', ['supervisor_person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supervisor_relationship_supervisor_person_id'), table_name='supervisor_relationship')
    op.drop_index(op.f('ix_supervisor_relationship_student_id'), table_name='supervisor_relationship')
    op.drop_table('supervisor_relationship')
    # ### end Alembic commands ###
