"""recruitment admissions student

Revision ID: 299453df7836
Revises: 9b1abbddf18d
Create Date: 2026-08-21 18:34:32.959489
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '299453df7836'
down_revision: Union[str, None] = '9b1abbddf18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department')),
    sa.UniqueConstraint('code', name=op.f('uq_department_code'))
    )
    op.create_table('programme',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_programme_department_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programme')),
    sa.UniqueConstraint('code', name=op.f('uq_programme_code'))
    )
    op.create_table('research_area',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_research_area_department_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_area')),
    sa.UniqueConstraint('code', name=op.f('uq_research_area_code'))
    )
    op.create_table('research_opportunity',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('research_area_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('principal_supervisor_id', sa.Uuid(), nullable=True),
    sa.Column('stipend_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('eligibility', sa.String(length=1000), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_duration_months', sa.Integer(), nullable=True),
    sa.Column('positions_available', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'open', 'recruiting', 'filled', 'closed', name='opportunity_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_research_opportunity_department_id_department')),
    sa.ForeignKeyConstraint(['principal_supervisor_id'], ['person.id'], name=op.f('fk_research_opportunity_principal_supervisor_id_person')),
    sa.ForeignKeyConstraint(['research_area_id'], ['research_area.id'], name=op.f('fk_research_opportunity_research_area_id_research_area')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_opportunity'))
    )
    op.create_table('student',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('student_ref', sa.String(length=40), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('research_area_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('study_mode', sa.Enum('full_time', 'part_time', name='study_mode'), nullable=False),
    sa.Column('status', sa.Enum('prospective', 'registered', 'active', 'on_leave', 'suspended', 'completed', 'withdrawn', 'terminated', name='student_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_student_department_id_department')),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_student_person_id_person')),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_student_programme_id_programme')),
    sa.ForeignKeyConstraint(['research_area_id'], ['research_area.id'], name=op.f('fk_student_research_area_id_research_area')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student')),
    sa.UniqueConstraint('student_ref', name=op.f('uq_student_student_ref'))
    )
    op.create_index(op.f('ix_student_person_id'), 'student', ['person_id'], unique=False)
    op.create_table('application',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('route', sa.Enum('opportunity_led', 'student_led', name='application_route'), nullable=False),
    sa.Column('research_opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('research_area_id', sa.Uuid(), nullable=True),
    sa.Column('proposal_document_ref', sa.String(length=500), nullable=True),
    sa.Column('current_stage', sa.Enum('prospect', 'applicant', 'under_assessment', 'shortlisted', 'interview', 'selected', 'offer_made', 'offer_accepted', 'rejected', 'withdrawn', 'converted', name='candidate_stage'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_application_person_id_person')),
    sa.ForeignKeyConstraint(['research_area_id'], ['research_area.id'], name=op.f('fk_application_research_area_id_research_area')),
    sa.ForeignKeyConstraint(['research_opportunity_id'], ['research_opportunity.id'], name=op.f('fk_application_research_opportunity_id_research_opportunity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application'))
    )
    op.create_index(op.f('ix_application_person_id'), 'application', ['person_id'], unique=False)
    op.create_table('research_project',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('research_topic', sa.String(length=500), nullable=True),
    sa.Column('research_group', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_research_project_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_project'))
    )
    op.create_index(op.f('ix_research_project_student_id'), 'research_project', ['student_id'], unique=False)
    op.create_table('application_assessment',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('assessor_user_id', sa.Uuid(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('rationale', sa.String(length=2000), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name=op.f('fk_application_assessment_application_id_application'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessor_user_id'], ['users.id'], name=op.f('fk_application_assessment_assessor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_assessment'))
    )
    op.create_index(op.f('ix_application_assessment_application_id'), 'application_assessment', ['application_id'], unique=False)
    op.create_table('candidate_stage_history',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage', sa.Enum('prospect', 'applicant', 'under_assessment', 'shortlisted', 'interview', 'selected', 'offer_made', 'offer_accepted', 'rejected', 'withdrawn', 'converted', name='candidate_stage'), nullable=True),
    sa.Column('to_stage', sa.Enum('prospect', 'applicant', 'under_assessment', 'shortlisted', 'interview', 'selected', 'offer_made', 'offer_accepted', 'rejected', 'withdrawn', 'converted', name='candidate_stage'), nullable=False),
    sa.Column('moved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name=op.f('fk_candidate_stage_history_application_id_application'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moved_by_user_id'], ['users.id'], name=op.f('fk_candidate_stage_history_moved_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_stage_history'))
    )
    op.create_index(op.f('ix_candidate_stage_history_application_id'), 'candidate_stage_history', ['application_id'], unique=False)
    op.create_table('offer',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'accepted', 'declined', 'expired', 'withdrawn', name='offer_status'), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name=op.f('fk_offer_application_id_application'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer'))
    )
    op.create_index(op.f('ix_offer_application_id'), 'offer', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_application_id'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_candidate_stage_history_application_id'), table_name='candidate_stage_history')
    op.drop_table('candidate_stage_history')
    op.drop_index(op.f('ix_application_assessment_application_id'), table_name='application_assessment')
    op.drop_table('application_assessment')
    op.drop_index(op.f('ix_research_project_student_id'), table_name='research_project')
    op.drop_table('research_project')
    op.drop_index(op.f('ix_application_person_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_student_person_id'), table_name='student')
    op.drop_table('student')
    op.drop_table('research_opportunity')
    op.drop_table('research_area')
    op.drop_table('programme')
    op.drop_table('department')
    # ### end Alembic commands ###
