"""phase4b funding: cost centres, stipend payments, fee waivers

Revision ID: 3a5a0cd9be93
Revises: cff59f95ecca
Create Date: 2026-08-22 00:04:44.166409
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a5a0cd9be93'
down_revision: Union[str, None] = 'cff59f95ecca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # payment_frequency is used by add_column below, which does not create the type itself.
    sa.Enum('monthly', 'quarterly', 'termly', 'annual', 'one_off', name='payment_frequency').create(
        op.get_bind(), checkfirst=True
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_waiver',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('arrangement_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('full_fee', 'partial_fee', 'bench_fee', name='waiver_kind'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('academic_year', sa.String(length=9), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_fee_waiver_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['arrangement_id'], ['funding_arrangement.id'], name=op.f('fk_fee_waiver_arrangement_id_funding_arrangement'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_fee_waiver_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_waiver'))
    )
    op.create_index(op.f('ix_fee_waiver_student_id'), 'fee_waiver', ['student_id'], unique=False)
    op.create_table('stipend_payment',
    sa.Column('arrangement_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'approved', 'paid', 'held', 'cancelled', name='payment_status'), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('finance_reference', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['arrangement_id'], ['funding_arrangement.id'], name=op.f('fk_stipend_payment_arrangement_id_funding_arrangement'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_stipend_payment_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stipend_payment'))
    )
    op.create_index(op.f('ix_stipend_payment_arrangement_id'), 'stipend_payment', ['arrangement_id'], unique=False)
    op.create_index('ix_stipend_payment_arrangement_status', 'stipend_payment', ['arrangement_id', 'status'], unique=False)
    op.create_index(op.f('ix_stipend_payment_due_date'), 'stipend_payment', ['due_date'], unique=False)
    op.create_index(op.f('ix_stipend_payment_student_id'), 'stipend_payment', ['student_id'], unique=False)
    op.add_column('funding_arrangement', sa.Column('cost_centre', sa.String(length=50), nullable=True))
    op.add_column('funding_arrangement', sa.Column('project_code', sa.String(length=50), nullable=True))
    op.add_column('funding_arrangement', sa.Column('funder_reference', sa.String(length=100), nullable=True))
    op.add_column('funding_arrangement', sa.Column('contribution_pct', sa.Integer(), nullable=True))
    op.add_column('funding_arrangement', sa.Column('payment_frequency', sa.Enum('monthly', 'quarterly', 'termly', 'annual', 'one_off', name='payment_frequency', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funding_arrangement', 'payment_frequency')
    op.drop_column('funding_arrangement', 'contribution_pct')
    op.drop_column('funding_arrangement', 'funder_reference')
    op.drop_column('funding_arrangement', 'project_code')
    op.drop_column('funding_arrangement', 'cost_centre')
    op.drop_index(op.f('ix_stipend_payment_student_id'), table_name='stipend_payment')
    op.drop_index(op.f('ix_stipend_payment_due_date'), table_name='stipend_payment')
    op.drop_index('ix_stipend_payment_arrangement_status', table_name='stipend_payment')
    op.drop_index(op.f('ix_stipend_payment_arrangement_id'), table_name='stipend_payment')
    op.drop_table('stipend_payment')
    op.drop_index(op.f('ix_fee_waiver_student_id'), table_name='fee_waiver')
    op.drop_table('fee_waiver')
    # ### end Alembic commands ###
