"""phase4b supervision: meeting log, capacity, end reason

Revision ID: 3f62e34f4e6f
Revises: 9716adbdff2d
Create Date: 2026-08-21 23:54:25.988190
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f62e34f4e6f'
down_revision: Union[str, None] = '9716adbdff2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervision_meeting',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('supervisor_person_id', sa.Uuid(), nullable=True),
    sa.Column('met_on', sa.Date(), nullable=False),
    sa.Column('format', sa.Enum('in_person', 'online', 'hybrid', name='meeting_format'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('next_meeting_on', sa.Date(), nullable=True),
    sa.Column('student_confirmed', sa.Boolean(), nullable=False),
    sa.Column('student_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_supervision_meeting_recorded_by_user_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_supervision_meeting_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_person_id'], ['person.id'], name=op.f('fk_supervision_meeting_supervisor_person_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supervision_meeting'))
    )
    op.create_index(op.f('ix_supervision_meeting_met_on'), 'supervision_meeting', ['met_on'], unique=False)
    op.create_index(op.f('ix_supervision_meeting_student_id'), 'supervision_meeting', ['student_id'], unique=False)
    op.add_column('supervisor_relationship', sa.Column('end_reason', sa.String(length=300), nullable=True))
    op.add_column('supervisor_relationship', sa.Column('weighting_pct', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supervisor_relationship', 'weighting_pct')
    op.drop_column('supervisor_relationship', 'end_reason')
    op.drop_index(op.f('ix_supervision_meeting_student_id'), table_name='supervision_meeting')
    op.drop_index(op.f('ix_supervision_meeting_met_on'), table_name='supervision_meeting')
    op.drop_table('supervision_meeting')
    # ### end Alembic commands ###
