"""progression

Revision ID: 4b0e9a184548
Revises: 1d606bec3a76
Create Date: 2026-08-21 19:15:21.538464
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b0e9a184548'
down_revision: Union[str, None] = '1d606bec3a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_definition',
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger', sa.JSON(), nullable=True),
    sa.Column('due_offset_days', sa.Integer(), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('review_panel', sa.JSON(), nullable=True),
    sa.Column('assessment_criteria', sa.JSON(), nullable=True),
    sa.Column('possible_outcomes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_milestone_definition_programme_id_programme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone_definition'))
    )
    op.create_index(op.f('ix_milestone_definition_programme_id'), 'milestone_definition', ['programme_id'], unique=False)
    op.create_table('milestone',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_definition_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'due', 'submitted', 'under_review', 'decided', 'overdue', name='milestone_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_definition_id'], ['milestone_definition.id'], name=op.f('fk_milestone_milestone_definition_id_milestone_definition')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_milestone_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone'))
    )
    op.create_index(op.f('ix_milestone_milestone_definition_id'), 'milestone', ['milestone_definition_id'], unique=False)
    op.create_index(op.f('ix_milestone_student_id'), 'milestone', ['student_id'], unique=False)
    op.create_table('progression_review',
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('student_submission_ref', sa.String(length=500), nullable=True),
    sa.Column('supervisor_assessment', sa.JSON(), nullable=True),
    sa.Column('panel_decision', sa.Enum('progress', 'progress_with_conditions', 'further_review', 'transfer_award', 'withdraw', 'terminate', name='progression_outcome'), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rationale', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_progression_review_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], name=op.f('fk_progression_review_milestone_id_milestone'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progression_review')),
    sa.UniqueConstraint('milestone_id', name=op.f('uq_progression_review_milestone_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progression_review')
    op.drop_index(op.f('ix_milestone_student_id'), table_name='milestone')
    op.drop_index(op.f('ix_milestone_milestone_definition_id'), table_name='milestone')
    op.drop_table('milestone')
    op.drop_index(op.f('ix_milestone_definition_programme_id'), table_name='milestone_definition')
    op.drop_table('milestone_definition')
    # ### end Alembic commands ###
