"""phase6.6 statutory report profiles and field mappings

Revision ID: 4b42a8cd5de3
Revises: 4f268aa13468
Create Date: 2026-08-22 11:13:02.005689
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b42a8cd5de3'
down_revision: Union[str, None] = '4f268aa13468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_profile',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_profile'))
    )
    op.create_index(op.f('ix_report_profile_academic_year'), 'report_profile', ['academic_year'], unique=False)
    op.create_index(op.f('ix_report_profile_code'), 'report_profile', ['code'], unique=False)
    op.create_index('uq_report_profile_version', 'report_profile', ['code', 'academic_year', 'version'], unique=True)
    op.create_table('report_field_mapping',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('target_field', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_expression', sa.String(length=200), nullable=False),
    sa.Column('transform', sa.String(length=40), nullable=True),
    sa.Column('default_value', sa.String(length=200), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['report_profile.id'], name=op.f('fk_report_field_mapping_profile_id_report_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_field_mapping'))
    )
    op.create_index(op.f('ix_report_field_mapping_profile_id'), 'report_field_mapping', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_field_mapping_profile_id'), table_name='report_field_mapping')
    op.drop_table('report_field_mapping')
    op.drop_index('uq_report_profile_version', table_name='report_profile')
    op.drop_index(op.f('ix_report_profile_code'), table_name='report_profile')
    op.drop_index(op.f('ix_report_profile_academic_year'), table_name='report_profile')
    op.drop_table('report_profile')
    # ### end Alembic commands ###
