"""phase6.3 funding lineage links

Revision ID: 4f268aa13468
Revises: 62447855ae7e
Create Date: 2026-08-22 11:03:23.574641
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4f268aa13468'
down_revision: Union[str, None] = '62447855ae7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funding_arrangement', sa.Column('research_award_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_funding_arrangement_research_award_id'), 'funding_arrangement', ['research_award_id'], unique=False)
    op.create_foreign_key(op.f('fk_funding_arrangement_research_award_id_research_award'), 'funding_arrangement', 'research_award', ['research_award_id'], ['id'], ondelete='SET NULL')
    op.add_column('research_project', sa.Column('research_award_id', sa.Uuid(), nullable=True))
    op.add_column('research_project', sa.Column('research_area_id', sa.Uuid(), nullable=True))
    op.add_column('research_project', sa.Column('research_opportunity_id', sa.Uuid(), nullable=True))
    op.add_column('research_project', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('research_project', sa.Column('end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_research_project_research_award_id'), 'research_project', ['research_award_id'], unique=False)
    op.create_foreign_key(op.f('fk_research_project_research_award_id_research_award'), 'research_project', 'research_award', ['research_award_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_research_project_research_opportunity_id_research_opportunity'), 'research_project', 'research_opportunity', ['research_opportunity_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_research_project_research_area_id_research_area'), 'research_project', 'research_area', ['research_area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_research_project_research_area_id_research_area'), 'research_project', type_='foreignkey')
    op.drop_constraint(op.f('fk_research_project_research_opportunity_id_research_opportunity'), 'research_project', type_='foreignkey')
    op.drop_constraint(op.f('fk_research_project_research_award_id_research_award'), 'research_project', type_='foreignkey')
    op.drop_index(op.f('ix_research_project_research_award_id'), table_name='research_project')
    op.drop_column('research_project', 'end_date')
    op.drop_column('research_project', 'start_date')
    op.drop_column('research_project', 'research_opportunity_id')
    op.drop_column('research_project', 'research_area_id')
    op.drop_column('research_project', 'research_award_id')
    op.drop_constraint(op.f('fk_funding_arrangement_research_award_id_research_award'), 'funding_arrangement', type_='foreignkey')
    op.drop_index(op.f('ix_funding_arrangement_research_award_id'), table_name='funding_arrangement')
    op.drop_column('funding_arrangement', 'research_award_id')
    # ### end Alembic commands ###
