"""workflow tasks notifications

Revision ID: 50d2f2bb3c2c
Revises: b2fc24516209
Create Date: 2026-08-21 20:11:01.482786
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50d2f2bb3c2c'
down_revision: Union[str, None] = 'b2fc24516209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_event',
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_event'))
    )
    op.create_index(op.f('ix_outbox_event_aggregate_type'), 'outbox_event', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_event_event_type'), 'outbox_event', ['event_type'], unique=False)
    op.create_table('notification',
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'read', 'failed', name='notification_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_notification_recipient_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_recipient_user_id'), 'notification', ['recipient_user_id'], unique=False)
    op.create_table('task',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('assignee_role', sa.String(length=100), nullable=True),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'blocked', 'done', 'cancelled', name='task_status'), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=True),
    sa.Column('aggregate_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_task_assignee_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.create_index(op.f('ix_task_assignee_role'), 'task', ['assignee_role'], unique=False)
    op.create_index(op.f('ix_task_assignee_user_id'), 'task', ['assignee_user_id'], unique=False)
    op.create_index('ix_task_role_status', 'task', ['assignee_role', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_role_status', table_name='task')
    op.drop_index(op.f('ix_task_assignee_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_assignee_role'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_notification_recipient_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_outbox_event_event_type'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_aggregate_type'), table_name='outbox_event')
    op.drop_table('outbox_event')
    # ### end Alembic commands ###
