"""examiner nomination

Revision ID: 58d983b42a5c
Revises: 5e9fa2d4a069
Create Date: 2026-08-21 20:28:11.698929
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '58d983b42a5c'
down_revision: Union[str, None] = '5e9fa2d4a069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examiner_nomination',
    sa.Column('thesis_id', sa.Uuid(), nullable=False),
    sa.Column('examiner_person_id', sa.Uuid(), nullable=False),
    sa.Column('examiner_type', sa.Enum('internal', 'external', name='examiner_type'), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_examiner_nomination_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['examiner_person_id'], ['person.id'], name=op.f('fk_examiner_nomination_examiner_person_id_person')),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], name=op.f('fk_examiner_nomination_thesis_id_thesis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_examiner_nomination'))
    )
    op.create_index(op.f('ix_examiner_nomination_thesis_id'), 'examiner_nomination', ['thesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examiner_nomination_thesis_id'), table_name='examiner_nomination')
    op.drop_table('examiner_nomination')
    # ### end Alembic commands ###
