"""funding

Revision ID: 5e149079b34f
Revises: 4b0e9a184548
Create Date: 2026-08-21 19:24:39.458446
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e149079b34f'
down_revision: Union[str, None] = '4b0e9a184548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_source',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('funder_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_source'))
    )
    op.create_table('funding_arrangement',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('funding_type', sa.Enum('research_council', 'university_scholarship', 'external', 'self_funded', name='funding_type'), nullable=False),
    sa.Column('funding_source_id', sa.Uuid(), nullable=True),
    sa.Column('stipend_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'changed', 'ended', name='funding_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funding_source_id'], ['funding_source.id'], name=op.f('fk_funding_arrangement_funding_source_id_funding_source')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_funding_arrangement_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_arrangement'))
    )
    op.create_index(op.f('ix_funding_arrangement_student_id'), 'funding_arrangement', ['student_id'], unique=False)
    op.create_index('ix_funding_arrangement_student_status', 'funding_arrangement', ['student_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_funding_arrangement_student_status', table_name='funding_arrangement')
    op.drop_index(op.f('ix_funding_arrangement_student_id'), table_name='funding_arrangement')
    op.drop_table('funding_arrangement')
    op.drop_table('funding_source')
    # ### end Alembic commands ###
