"""integration log

Revision ID: 5e9fa2d4a069
Revises: 50d2f2bb3c2c
Create Date: 2026-08-21 20:19:24.386410
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e9fa2d4a069'
down_revision: Union[str, None] = '50d2f2bb3c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_log',
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='integration_direction'), nullable=False),
    sa.Column('system', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=True),
    sa.Column('aggregate_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', 'skipped', 'duplicate', name='integration_status'), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_log'))
    )
    op.create_index(op.f('ix_integration_log_system'), 'integration_log', ['system'], unique=False)
    op.create_index('uq_integration_inbound', 'integration_log', ['system', 'source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_integration_inbound', table_name='integration_log')
    op.drop_index(op.f('ix_integration_log_system'), table_name='integration_log')
    op.drop_table('integration_log')
    # ### end Alembic commands ###
