"""phase6.1 research award, research demand, position provenance

Revision ID: 62447855ae7e
Revises: bc175392603e
Create Date: 2026-08-22 10:41:13.481239
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '62447855ae7e'
down_revision: Union[str, None] = 'bc175392603e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_award',
    sa.Column('award_ref', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('funder_id', sa.Uuid(), nullable=True),
    sa.Column('principal_investigator_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'closed', name='award_status'), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funder_id'], ['funding_source.id'], name=op.f('fk_research_award_funder_id_funding_source')),
    sa.ForeignKeyConstraint(['principal_investigator_id'], ['person.id'], name=op.f('fk_research_award_principal_investigator_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_award'))
    )
    op.create_index(op.f('ix_research_award_award_ref'), 'research_award', ['award_ref'], unique=True)
    op.create_index(op.f('ix_research_award_source_system'), 'research_award', ['source_system'], unique=False)
    op.create_table('research_demand',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('research_award_id', sa.Uuid(), nullable=True),
    sa.Column('research_area_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('requested_places', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('target_start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('identified', 'approved', 'positioned', 'filled', 'withdrawn', name='demand_status'), nullable=False),
    sa.Column('raised_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_research_demand_department_id_department')),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], name=op.f('fk_research_demand_raised_by_user_id_users')),
    sa.ForeignKeyConstraint(['research_area_id'], ['research_area.id'], name=op.f('fk_research_demand_research_area_id_research_area')),
    sa.ForeignKeyConstraint(['research_award_id'], ['research_award.id'], name=op.f('fk_research_demand_research_award_id_research_award'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_demand'))
    )
    op.create_index(op.f('ix_research_demand_research_award_id'), 'research_demand', ['research_award_id'], unique=False)
    op.create_index(op.f('ix_research_demand_status'), 'research_demand', ['status'], unique=False)
    op.add_column('research_opportunity', sa.Column('research_demand_id', sa.Uuid(), nullable=True))
    op.add_column('research_opportunity', sa.Column('research_award_id', sa.Uuid(), nullable=True))
    # Existing positions have taken no places yet under the new counter.
    op.add_column('research_opportunity', sa.Column('positions_filled', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_research_opportunity_research_award_id'), 'research_opportunity', ['research_award_id'], unique=False)
    op.create_index(op.f('ix_research_opportunity_research_demand_id'), 'research_opportunity', ['research_demand_id'], unique=False)
    op.create_foreign_key(op.f('fk_research_opportunity_research_award_id_research_award'), 'research_opportunity', 'research_award', ['research_award_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_research_opportunity_research_demand_id_research_demand'), 'research_opportunity', 'research_demand', ['research_demand_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_research_opportunity_research_demand_id_research_demand'), 'research_opportunity', type_='foreignkey')
    op.drop_constraint(op.f('fk_research_opportunity_research_award_id_research_award'), 'research_opportunity', type_='foreignkey')
    op.drop_index(op.f('ix_research_opportunity_research_demand_id'), table_name='research_opportunity')
    op.drop_index(op.f('ix_research_opportunity_research_award_id'), table_name='research_opportunity')
    op.drop_column('research_opportunity', 'positions_filled')
    op.drop_column('research_opportunity', 'research_award_id')
    op.drop_column('research_opportunity', 'research_demand_id')
    op.drop_index(op.f('ix_research_demand_status'), table_name='research_demand')
    op.drop_index(op.f('ix_research_demand_research_award_id'), table_name='research_demand')
    op.drop_table('research_demand')
    op.drop_index(op.f('ix_research_award_source_system'), table_name='research_award')
    op.drop_index(op.f('ix_research_award_award_ref'), table_name='research_award')
    op.drop_table('research_award')
    # ### end Alembic commands ###
