"""phase8_institution_settings

Revision ID: 800191647194
Revises: 4b42a8cd5de3
Create Date: 2026-08-22 14:44:29.059840
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '800191647194'
down_revision: Union[str, None] = '4b42a8cd5de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_institution_setting_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institution_setting'))
    )
    op.create_index(op.f('ix_institution_setting_key'), 'institution_setting', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_setting_key'), table_name='institution_setting')
    op.drop_table('institution_setting')
    # ### end Alembic commands ###
