"""phase4b thesis: examiner CoI, viva scheduling, corrections

Revision ID: 9716adbdff2d
Revises: 72da2f21478b
Create Date: 2026-08-21 23:45:35.611103
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9716adbdff2d'
down_revision: Union[str, None] = '72da2f21478b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    # New enum type must exist before it's used in a column (Postgres). SQLite ignores this.
    viva_format = sa.Enum('in_person', 'online', 'hybrid', name='viva_format')
    viva_format.create(bind, checkfirst=True)
    # Alembic doesn't autogenerate enum-value additions; add the new examiner_type value on PG.
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TYPE examiner_type ADD VALUE IF NOT EXISTS 'independent_chair'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesis_correction',
    sa.Column('thesis_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('minor', 'major', name='correction_kind'), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_thesis_correction_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], name=op.f('fk_thesis_correction_thesis_id_thesis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thesis_correction'))
    )
    op.create_index(op.f('ix_thesis_correction_thesis_id'), 'thesis_correction', ['thesis_id'], unique=False)
    op.add_column('examination', sa.Column('viva_location', sa.String(length=200), nullable=True))
    op.add_column('examination', sa.Column('viva_format', sa.Enum('in_person', 'online', 'hybrid', name='viva_format', create_type=False), nullable=True))
    op.add_column('examination', sa.Column('viva_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('examiner_nomination', sa.Column('affiliation', sa.String(length=200), nullable=True))
    op.add_column('examiner_nomination', sa.Column('conflict_of_interest', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('examiner_nomination', sa.Column('conflict_note', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examiner_nomination', 'conflict_note')
    op.drop_column('examiner_nomination', 'conflict_of_interest')
    op.drop_column('examiner_nomination', 'affiliation')
    op.drop_column('examination', 'viva_scheduled_at')
    op.drop_column('examination', 'viva_format')
    op.drop_column('examination', 'viva_location')
    op.drop_index(op.f('ix_thesis_correction_thesis_id'), table_name='thesis_correction')
    op.drop_table('thesis_correction')
    # ### end Alembic commands ###
