"""thesis completion

Revision ID: b2fc24516209
Revises: 5e149079b34f
Create Date: 2026-08-21 19:32:58.216262
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2fc24516209'
down_revision: Union[str, None] = '5e149079b34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('award_type', sa.String(length=50), nullable=True),
    sa.Column('conferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_award_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_award'))
    )
    op.create_index(op.f('ix_award_student_id'), 'award', ['student_id'], unique=False)
    op.create_table('completion',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'requirements_met', 'award_confirmed', 'graduated', name='completion_status'), nullable=False),
    sa.Column('requirements_met_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('award_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_completion_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_completion'))
    )
    op.create_index(op.f('ix_completion_student_id'), 'completion', ['student_id'], unique=True)
    op.create_table('thesis',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('preparation', 'intention_to_submit', 'submitted', 'under_examination', 'corrections', 'resubmission', 'approved', 'failed', name='thesis_status'), nullable=False),
    sa.Column('intention_to_submit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_ref', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_thesis_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thesis'))
    )
    op.create_index(op.f('ix_thesis_student_id'), 'thesis', ['student_id'], unique=True)
    op.create_table('examination',
    sa.Column('thesis_id', sa.Uuid(), nullable=False),
    sa.Column('viva_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.Enum('pass_', 'pass_with_corrections', 'major_corrections', 'resubmission', 'fail', name='examination_outcome'), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], name=op.f('fk_examination_thesis_id_thesis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_examination'))
    )
    op.create_index(op.f('ix_examination_thesis_id'), 'examination', ['thesis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examination_thesis_id'), table_name='examination')
    op.drop_table('examination')
    op.drop_index(op.f('ix_thesis_student_id'), table_name='thesis')
    op.drop_table('thesis')
    op.drop_index(op.f('ix_completion_student_id'), table_name='completion')
    op.drop_table('completion')
    op.drop_index(op.f('ix_award_student_id'), table_name='award')
    op.drop_table('award')
    # ### end Alembic commands ###
