"""phase6.5 student lifecycle events (suspension, extension, mode change)

Revision ID: bc175392603e
Revises: 3a5a0cd9be93
Create Date: 2026-08-22 10:01:56.362538
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'bc175392603e'
down_revision: Union[str, None] = '3a5a0cd9be93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Reference the pre-existing study_mode type without trying to create it.
_study_mode = postgresql.ENUM('full_time', 'part_time', name='study_mode', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_lifecycle_event',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('suspension', 'extension', 'mode_change', name='lifecycle_event_type'), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'cancelled', name='lifecycle_event_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('extension_days', sa.Integer(), nullable=True),
    # study_mode already exists (created with the student table). A generic sa.Enum would emit
    # CREATE TYPE again, so reference the existing type explicitly instead.
    sa.Column('previous_mode', _study_mode, nullable=True),
    sa.Column('new_mode', _study_mode, nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('days_applied', sa.Integer(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_student_lifecycle_event_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_student_lifecycle_event_requested_by_user_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_lifecycle_event_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_lifecycle_event'))
    )
    op.create_index(op.f('ix_student_lifecycle_event_status'), 'student_lifecycle_event', ['status'], unique=False)
    op.create_index(op.f('ix_student_lifecycle_event_student_id'), 'student_lifecycle_event', ['student_id'], unique=False)
    op.add_column('student', sa.Column('original_expected_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'original_expected_end_date')
    op.drop_index(op.f('ix_student_lifecycle_event_student_id'), table_name='student_lifecycle_event')
    op.drop_index(op.f('ix_student_lifecycle_event_status'), table_name='student_lifecycle_event')
    op.drop_table('student_lifecycle_event')
    # ### end Alembic commands ###
