"""exports and workflow definitions

Revision ID: cca5baf81f1d
Revises: 58d983b42a5c
Create Date: 2026-08-21 22:34:41.485223
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cca5baf81f1d'
down_revision: Union[str, None] = '58d983b42a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_job',
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'complete', 'failed', name='export_status'), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_job'))
    )
    op.create_index(op.f('ix_export_job_kind'), 'export_job', ['kind'], unique=False)
    op.create_table('workflow_definition',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('initial_state', sa.String(length=80), nullable=False),
    sa.Column('states', sa.JSON(), nullable=False),
    sa.Column('transitions', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_definition'))
    )
    op.create_index(op.f('ix_workflow_definition_key'), 'workflow_definition', ['key'], unique=False)
    op.create_index('uq_workflow_def_key_version', 'workflow_definition', ['key', 'version'], unique=True)
    op.create_table('workflow_instance',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('current_state', sa.String(length=80), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], name=op.f('fk_workflow_instance_definition_id_workflow_definition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_instance'))
    )
    op.create_index(op.f('ix_workflow_instance_definition_id'), 'workflow_instance', ['definition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_instance_definition_id'), table_name='workflow_instance')
    op.drop_table('workflow_instance')
    op.drop_index('uq_workflow_def_key_version', table_name='workflow_definition')
    op.drop_index(op.f('ix_workflow_definition_key'), table_name='workflow_definition')
    op.drop_table('workflow_definition')
    op.drop_index(op.f('ix_export_job_kind'), table_name='export_job')
    op.drop_table('export_job')
    # ### end Alembic commands ###
