"""phase4b progression: panel, conditions, outcome letter, appeals

Revision ID: cff59f95ecca
Revises: 3f62e34f4e6f
Create Date: 2026-08-22 00:00:33.526835
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cff59f95ecca'
down_revision: Union[str, None] = '3f62e34f4e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progression_appeal',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('grounds', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'upheld', 'rejected', 'withdrawn', name='appeal_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_progression_appeal_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['review_id'], ['progression_review.id'], name=op.f('fk_progression_appeal_review_id_progression_review'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_progression_appeal_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progression_appeal'))
    )
    op.create_index(op.f('ix_progression_appeal_review_id'), 'progression_appeal', ['review_id'], unique=False)
    op.create_index(op.f('ix_progression_appeal_student_id'), 'progression_appeal', ['student_id'], unique=False)
    op.create_table('review_panel_member',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('chair', 'internal_assessor', 'independent_assessor', 'supervisor_observer', name='panel_role'), nullable=False),
    sa.Column('is_independent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_review_panel_member_person_id_person')),
    sa.ForeignKeyConstraint(['review_id'], ['progression_review.id'], name=op.f('fk_review_panel_member_review_id_progression_review'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_panel_member'))
    )
    op.create_index(op.f('ix_review_panel_member_person_id'), 'review_panel_member', ['person_id'], unique=False)
    op.create_index(op.f('ix_review_panel_member_review_id'), 'review_panel_member', ['review_id'], unique=False)
    op.add_column('progression_review', sa.Column('conditions', sa.Text(), nullable=True))
    op.add_column('progression_review', sa.Column('re_review_due', sa.Date(), nullable=True))
    op.add_column('progression_review', sa.Column('conditions_met_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('progression_review', sa.Column('outcome_letter', sa.Text(), nullable=True))
    op.add_column('progression_review', sa.Column('appeal_deadline', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progression_review', 'appeal_deadline')
    op.drop_column('progression_review', 'outcome_letter')
    op.drop_column('progression_review', 'conditions_met_at')
    op.drop_column('progression_review', 're_review_due')
    op.drop_column('progression_review', 'conditions')
    op.drop_index(op.f('ix_review_panel_member_review_id'), table_name='review_panel_member')
    op.drop_index(op.f('ix_review_panel_member_person_id'), table_name='review_panel_member')
    op.drop_table('review_panel_member')
    op.drop_index(op.f('ix_progression_appeal_student_id'), table_name='progression_appeal')
    op.drop_index(op.f('ix_progression_appeal_review_id'), table_name='progression_appeal')
    op.drop_table('progression_appeal')
    # ### end Alembic commands ###
