"""pl3_models_versions_runs

Revision ID: d1affdf74011
Revises: ddba4187dd3c
Create Date: 2026-08-22 16:06:18.646168
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1affdf74011'
down_revision: Union[str, None] = 'ddba4187dd3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model',
    sa.Column('target_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_ml_model_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_model')),
    sa.UniqueConstraint('name', name=op.f('uq_ml_model_name'))
    )
    op.create_index(op.f('ix_ml_model_target_key'), 'ml_model', ['target_key'], unique=False)
    op.create_table('ml_training_run',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('started_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['ml_dataset.id'], name=op.f('fk_ml_training_run_dataset_id_ml_dataset')),
    sa.ForeignKeyConstraint(['model_id'], ['ml_model.id'], name=op.f('fk_ml_training_run_model_id_ml_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], name=op.f('fk_ml_training_run_started_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_training_run'))
    )
    op.create_index(op.f('ix_ml_training_run_dataset_id'), 'ml_training_run', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ml_training_run_model_id'), 'ml_training_run', ['model_id'], unique=False)
    op.create_table('ml_model_version',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('training_run_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=80), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('feature_keys', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('beats_baseline', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('artifact', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_model.id'], name=op.f('fk_ml_model_version_model_id_ml_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_run_id'], ['ml_training_run.id'], name=op.f('fk_ml_model_version_training_run_id_ml_training_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_model_version'))
    )
    op.create_index(op.f('ix_ml_model_version_model_id'), 'ml_model_version', ['model_id'], unique=False)
    op.create_index(op.f('ix_ml_model_version_status'), 'ml_model_version', ['status'], unique=False)
    op.create_index(op.f('ix_ml_model_version_training_run_id'), 'ml_model_version', ['training_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_model_version_training_run_id'), table_name='ml_model_version')
    op.drop_index(op.f('ix_ml_model_version_status'), table_name='ml_model_version')
    op.drop_index(op.f('ix_ml_model_version_model_id'), table_name='ml_model_version')
    op.drop_table('ml_model_version')
    op.drop_index(op.f('ix_ml_training_run_model_id'), table_name='ml_training_run')
    op.drop_index(op.f('ix_ml_training_run_dataset_id'), table_name='ml_training_run')
    op.drop_table('ml_training_run')
    op.drop_index(op.f('ix_ml_model_target_key'), table_name='ml_model')
    op.drop_table('ml_model')
    # ### end Alembic commands ###
