"""pl4_governance_columns

Revision ID: d81f2647288f
Revises: d1affdf74011
Create Date: 2026-08-22 16:25:49.992006
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd81f2647288f'
down_revision: Union[str, None] = 'd1affdf74011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_model_version', sa.Column('decided_by_user_id', sa.Uuid(), nullable=True))
    op.add_column('ml_model_version', sa.Column('decision_rationale', sa.Text(), nullable=True))
    op.add_column('ml_model_version', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ml_model_version', sa.Column('governance_log', sa.JSON(), nullable=False, server_default='[]'))
    op.create_foreign_key(op.f('fk_ml_model_version_decided_by_user_id_users'), 'ml_model_version', 'users', ['decided_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ml_model_version_decided_by_user_id_users'), 'ml_model_version', type_='foreignkey')
    op.drop_column('ml_model_version', 'governance_log')
    op.drop_column('ml_model_version', 'decided_at')
    op.drop_column('ml_model_version', 'decision_rationale')
    op.drop_column('ml_model_version', 'decided_by_user_id')
    # ### end Alembic commands ###
